### ISSUE TITLE
Pickups do not go into extended inventory

### ISSUE THREAD

**Issue by T0RNATO** [HB0P/Balanced-Inventory#1]
After setting the config value `  "restrictExtendedInventoryToEquipment": false`, items picked up off the floor do not enter the additional inventory slots, they must be manually moved there.

(Very cool mod btw though)

**Comment by HB0P** [comment]
Thanks, I'll work on this (also shift-clicking I think has issues) and hopefully get it fixed in the next week or so

**Comment by HB0P** [comment]
This is fixed along with a couple of other bugs in version 1.0.2, which is now out on modrinth
